<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Glossary
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<script type="text/javascript">
//<![CDATA[
(function() {
    if (typeof window.fishpigGlossaryIncluded !== 'undefined') {
        return;
    }

    window.fishpigGlossaryIncluded = true;
    
    const data = <?php echo $this->getJsonDataObject() ?>;
    let links = document.querySelectorAll('a.gls');
    
    for (let i = 0; i < links.length; i++) {
        let elem = links[i];
        let className = elem.getAttribute('class');
        let m = className.match(/gls-([0-9]+)/);
        
        if (m) {
            let wordId = m[1];
            let definition = elem.getAttribute('definition') || data[wordId];
            
            if (definition) {
                elem.setAttribute('title', definition);
            }
        }
    }
})();
//]]>
</script>
