<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Glossary
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<script type="text/javascript">
//<![CDATA[
(function() {
    if (typeof window.fishpigGlossaryIncluded !== 'undefined') {
        return;
    }

    window.fishpigGlossaryIncluded = true;
    
    var data = <?php echo $this->getJsonDataObject() ?>;
    var links = $$('a.gls');
    
    links.each(function(elem) {
        var m = elem.readAttribute('class').match(/gls-([0-9]+)/);
        
        if (m) {
            var wordId = m[1];
            var definition = elem.readAttribute('definition') || data[wordId];
            
            if (definition) {
                elem.writeAttribute('title', definition);
            }
        }
    });
})();
//]]>
</script>