<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Glossary
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="page-title">
	<h1><?php echo Mage::helper('glossary')->getPageTitle() ?: $this->__('Glossary') ?></h1>
</div>
<?php if ($words = $this->getWords()): ?>
	<div class="gls">
		<?php echo $this->getNavigationHtml() ?>
		<ul class="word-list">
			<?php foreach($words as $word): ?>
				<?php if ($this->canPrintAnchor($word->getFirstCharacter())): ?>
					<li id="<?php echo $word->getFirstCharacter() ?>" class="title"><span><?php echo $word->getFirstCharacter() ?></span> <a href="#top"><?php echo $this->__('Back to top') ?></a></li>
				<?php endif; ?>
				<li class="item">
					<p><a href="<?php echo $word->getUrl() ?>" title="<?php echo $this->escapeHtml($word->getWord()) ?>"><?php echo $this->escapeHtml($word->getWord()) ?></a><?php if ($shortDefinition = $word->getShortDefinition()): ?> - <?php echo nl2br($shortDefinition) ?><?php endif; ?>
				</li>
			<?php endforeach; ?>	
		</ul>
	</div>
<?php endif; ?>

<script type="application/ld+json">
<?php echo $this->getCollectionPageJsonLd() ?>
</script>